### ISSUE TITLE
Automatic download version update

### ISSUE THREAD

**Issue by NejcDebevec** [biolab/scorange-hugo#98]
Every time the new version of scOrange in available, the version in the download button should be updated.

**Comment by BlazZupan** [comment]
At this stage it would suffice if there is an md file somwhere in the hierarchy that stores the latest version number, like 0.9.5. Than, the contents of this file is used to render the label of the download button in the Download page, like "Download scOrange 0.9.5".

**Comment by NejcDebevec** [comment]
@BlazZupan Idea with the`.md` file is already implemented. You can change the version of the download button in `/content/download/_index.md.`
